### ISSUE TITLE
Some concat layers don't work

### ISSUE THREAD

**Issue by crowsonkb** [pertusa/InceptionBN-21K-for-Caffe#1]
An example error:

```
F1015 21:27:53.828809 3034956736 concat_layer.cpp:42] Check failed: top_shape[j] == bottom[i]->shape(j) (9 vs. 8) All inputs must have the same shape, except at concat_axis.
```

**Comment by crowsonkb** [comment]
Specifically anything from `ch_concat_3c_chconcat` on doesn't work for me.

**Comment by crowsonkb** [comment]
Also, the version of deploy.prototxt from before commit https://github.com/pertusa/InceptionBN-21K-for-Caffe/commit/cec7e092feef6e3aaf732c6fc30f4f70491747f5 doesn't work for me either.

**Comment by pertusa** [comment]
The initial commit of the model at http://www.dlsi.ua.es/~pertusa/deep/Inception21k.caffemodel had this issue, please try to download the model again (fixed on Sep. 16 in commit be8d78c). If the problem persists, it may be due to wrong image dimensions at the input layer. The input image should be resized to 224x224. Unlike other networks, the Inception21k architecture doesn't allow to use variable image sizes.
